[pytest]
testpaths = tests
asyncio_mode = auto
norecursedirs = .git .pytest_cache __pycache__ pytest-cache-files-*
filterwarnings =
    ignore:'asyncio\.get_event_loop_policy' is deprecated and slated for removal in Python 3\.16:DeprecationWarning:pytest_asyncio\.plugin
