from __future__ import annotations

MOCK_CRISIS_SOURCE = ["phase5_mock_crisis_dataset"]
MOCK_CRISIS_SOURCE_DATE = "2026-04-24"

MOCK_CRISIS_SCENARIOS = {
    "normal": {
        "vix": 17.5,
        "vix_spike_pct": 3.0,
        "oil_price_spike_5d_pct": 1.2,
        "gold_price_spike_5d_pct": 0.8,
        "dxy_spike_5d_pct": 0.4,
        "treasury_yield_movement": "stable",
        "geopolitical_news_count": 2,
        "geopolitical_news_count_benchmark": 8,
        "geopolitical_news_severity": "low",
        "defense_energy_relative_strength": "stable",
        "global_equity_volatility": "normal",
    },
    "elevated": {
        "vix": 26.0,
        "vix_spike_pct": 18.0,
        "oil_price_spike_5d_pct": 5.5,
        "gold_price_spike_5d_pct": 1.2,
        "dxy_spike_5d_pct": 0.8,
        "treasury_yield_movement": "falling",
        "geopolitical_news_count": 11,
        "geopolitical_news_count_benchmark": 8,
        "geopolitical_news_severity": "low",
        "defense_energy_relative_strength": "firm",
        "global_equity_volatility": "elevated",
    },
    "high": {
        "vix": 33.0,
        "vix_spike_pct": 32.0,
        "oil_price_spike_5d_pct": 6.5,
        "gold_price_spike_5d_pct": 4.2,
        "dxy_spike_5d_pct": 3.5,
        "treasury_yield_movement": "falling",
        "geopolitical_news_count": 18,
        "geopolitical_news_count_benchmark": 8,
        "geopolitical_news_severity": "medium",
        "defense_energy_relative_strength": "strong",
        "global_equity_volatility": "high",
    },
    "severe": {
        "vix": 43.0,
        "vix_spike_pct": 55.0,
        "oil_price_spike_5d_pct": 12.0,
        "gold_price_spike_5d_pct": 5.0,
        "dxy_spike_5d_pct": 4.0,
        "treasury_yield_movement": "falling",
        "geopolitical_news_count": 30,
        "geopolitical_news_count_benchmark": 8,
        "geopolitical_news_severity": "high",
        "defense_energy_relative_strength": "strong",
        "global_equity_volatility": "severe",
    },
    "insufficient_data": {
        "vix": None,
        "vix_spike_pct": None,
        "oil_price_spike_5d_pct": None,
        "gold_price_spike_5d_pct": None,
        "dxy_spike_5d_pct": None,
        "treasury_yield_movement": None,
        "geopolitical_news_count": None,
        "geopolitical_news_count_benchmark": None,
        "geopolitical_news_severity": None,
        "defense_energy_relative_strength": None,
        "global_equity_volatility": None,
    },
}
