from __future__ import annotations

MOCK_SOURCE_DATE = "2026-04-24"
MOCK_SOURCE = ["phase1_mock_dataset"]


MARKET_SNAPSHOTS = {
    "normal": {
        "vix": 17.8,
        "vix_recent_spike": False,
        "vix_trend": "stable",
        "vix_falling_from_spike": False,
        "fear_greed": 48,
        "sp500_drawdown_pct": -4.2,
        "nasdaq_drawdown_pct": -6.1,
        "index_gain_vs_prior_cycle_high": 4.0,
        "index_gain_from_recent_trough": 11.5,
        "distance_from_52w_high": -4.2,
        "index_extension_from_200d_pct": 4.8,
        "index_range_20d_pct": 6.4,
        "realized_vol_20d": 13.2,
        "previous_realized_vol_20d": 14.1,
        "days_since_low": 42,
        "dxy_30d_change_pct": 0.4,
        "ten_year_two_year_spread_bps": 18,
        "fed_policy_state": "steady",
        "consecutive_rate_cut_count": 0,
        "rate_trend": "steady",
        "cash_to_market_cap_pct": None,
        "revenue_growth_yoy_pct": None,
        "revenue_cagr_3y_pct": None,
        "founder_is_ceo": False,
        "net_insider_buy_value_180d": 0,
        "insider_buy_count_180d": 0,
        "user_reported_social_heat": "low",
        "theme_mentions_7d": 76,
        "theme_mentions_30d_avg": 58,
        "media_hype_ratio": 1.1,
        "youtube_hype_ratio": 1.0,
        "geopolitical_headline_count": 2,
    },
    "fearful": {
        "vix": 33.5,
        "vix_recent_spike": True,
        "vix_trend": "falling",
        "vix_falling_from_spike": True,
        "fear_greed": 16,
        "sp500_drawdown_pct": -22.4,
        "nasdaq_drawdown_pct": -28.7,
        "index_gain_vs_prior_cycle_high": -18.0,
        "index_gain_from_recent_trough": 8.2,
        "distance_from_52w_high": -22.4,
        "index_extension_from_200d_pct": -18.0,
        "index_range_20d_pct": 7.2,
        "realized_vol_20d": 27.5,
        "previous_realized_vol_20d": 34.0,
        "days_since_low": 28,
        "dxy_30d_change_pct": 3.7,
        "ten_year_two_year_spread_bps": -42,
        "fed_policy_state": "easing_watch",
        "consecutive_rate_cut_count": 2,
        "rate_trend": "easing",
        "cash_to_market_cap_pct": 12.0,
        "revenue_growth_yoy_pct": [14.0, 16.0, 18.0],
        "revenue_cagr_3y_pct": 16.0,
        "founder_is_ceo": True,
        "net_insider_buy_value_180d": 1250000,
        "insider_buy_count_180d": 2,
        "user_reported_social_heat": "low",
        "theme_mentions_7d": 41,
        "theme_mentions_30d_avg": 55,
        "media_hype_ratio": 0.8,
        "youtube_hype_ratio": 0.6,
        "geopolitical_headline_count": 12,
    },
    "overheated": {
        "vix": 13.1,
        "vix_recent_spike": False,
        "vix_trend": "stable",
        "vix_falling_from_spike": False,
        "fear_greed": 86,
        "sp500_drawdown_pct": 0.0,
        "nasdaq_drawdown_pct": 0.0,
        "index_gain_vs_prior_cycle_high": 34.0,
        "index_gain_from_recent_trough": 48.0,
        "distance_from_52w_high": 0.0,
        "index_extension_from_200d_pct": 31.5,
        "index_range_20d_pct": 14.2,
        "realized_vol_20d": 19.5,
        "previous_realized_vol_20d": 14.8,
        "days_since_low": 185,
        "dxy_30d_change_pct": -1.2,
        "ten_year_two_year_spread_bps": 28,
        "fed_policy_state": "steady",
        "consecutive_rate_cut_count": 0,
        "rate_trend": "steady",
        "cash_to_market_cap_pct": 3.0,
        "revenue_growth_yoy_pct": [18.0, 21.0, 25.0],
        "revenue_cagr_3y_pct": 21.2,
        "founder_is_ceo": True,
        "net_insider_buy_value_180d": 0,
        "insider_buy_count_180d": 0,
        "user_reported_social_heat": "high",
        "theme_mentions_7d": 210,
        "theme_mentions_30d_avg": 72,
        "media_hype_ratio": 3.4,
        "youtube_hype_ratio": 3.1,
        "geopolitical_headline_count": 1,
    },
}


THEMES = [
    {
        "theme": "AI energy infrastructure",
        "candidate_companies": ["ETN", "VRT", "GEV"],
        "theme_mentions_7d": 76,
        "theme_mentions_30d_avg": 58,
        "news_momentum_score": 86,
        "capital_flow_score": 82,
        "policy_support_score": 78,
        "technology_progress_score": 88,
        "commercialization_score": 80,
        "strategic_relevance_score": 94,
        "missing_data": ["live theme news source", "live capital flow source"],
    },
    {
        "theme": "data center cooling",
        "candidate_companies": ["VRT", "TT"],
        "theme_mentions_7d": 62,
        "theme_mentions_30d_avg": 44,
        "news_momentum_score": 80,
        "capital_flow_score": 74,
        "policy_support_score": 66,
        "technology_progress_score": 82,
        "commercialization_score": 78,
        "strategic_relevance_score": 88,
        "missing_data": ["live customer contract source"],
    },
    {
        "theme": "stablecoin / payment rails",
        "candidate_companies": ["V", "MA", "COIN"],
        "theme_mentions_7d": 54,
        "theme_mentions_30d_avg": 40,
        "news_momentum_score": 76,
        "capital_flow_score": 78,
        "policy_support_score": 72,
        "technology_progress_score": 68,
        "commercialization_score": 74,
        "strategic_relevance_score": 86,
        "missing_data": ["live stablecoin supply source"],
    },
    {
        "theme": "humanoid robotics",
        "candidate_companies": ["TER", "ROK"],
        "theme_mentions_7d": 41,
        "theme_mentions_30d_avg": 38,
        "news_momentum_score": 64,
        "capital_flow_score": 62,
        "policy_support_score": 54,
        "technology_progress_score": 76,
        "commercialization_score": 58,
        "strategic_relevance_score": 78,
        "missing_data": ["live production scale source"],
    },
    {
        "theme": "cybersecurity / blockchain",
        "candidate_companies": ["CRWD", "PANW"],
        "theme_mentions_7d": 36,
        "theme_mentions_30d_avg": 34,
        "news_momentum_score": 58,
        "capital_flow_score": 60,
        "policy_support_score": 50,
        "technology_progress_score": 66,
        "commercialization_score": 70,
        "strategic_relevance_score": 72,
        "missing_data": ["live threat intelligence source"],
    },
]

MOCK_SMART_MONEY_SUMMARY = {
    "institutional_13f": {
        "institution_name": "Mock Growth Fund",
        "issuer_name": "US Mega Cap Basket",
        "cusip": "000000000",
        "shares": 1200000,
        "market_value": 185000000,
        "quarter": "2026-Q1",
        "filing_date": "2026-05-15",
        "holder_count": 218,
        "holder_count_change": 6,
        "top_10_holder_concentration": 0.32,
        "quarterly_position_change_pct": 4.5,
        "institutional_ownership_proxy": 0.61,
        "peer_average_institutional_ownership": 0.54,
        "peer_average_quarterly_position_change_pct": 2.0,
        "sector_median_institutional_ownership": 0.57,
    },
    "form4_transactions": [
        {
            "insider_name": "Mock Director A",
            "role": "Director",
            "transaction_code": "P",
            "transaction_type": "accumulation",
            "shares": 1200,
            "price": 80.5,
            "value": 96600,
            "transaction_date": "2026-04-10",
            "filing_date": "2026-04-12",
        }
    ],
    "options_activity": {
        "option_volume": 42000,
        "open_interest": 21000,
        "call_put_ratio": 1.8,
        "implied_volatility": 0.42,
        "expiration_date": "2026-06-19",
        "abnormal_volume_ratio": 2.1,
        "direction_consistent_with_price_action": False,
    },
}


STOCK_FIXTURES = {
    "NVDA": {
        "company_name": "NVIDIA Corporation",
        "sector": "Information Technology",
        "themes": ["AI energy infrastructure", "data center cooling"],
        "leadership_points": 16.5,
        "revenue_cagr_3y_pct": 43.2,
        "cash_to_market_cap_pct": 3.6,
        "revenue_growth_yoy_pct": [61.0, 126.0, 114.0],
        "free_cash_flow_margin_pct": 38.1,
        "net_debt_to_ebitda": -0.4,
        "founder_is_ceo": True,
        "net_insider_buy_value_180d": 0,
        "insider_buy_count_180d": 0,
        "vix": 17.8,
        "vix_recent_spike": False,
        "vix_trend": "stable",
        "vix_falling_from_spike": False,
        "fear_greed": 48,
        "sp500_drawdown_pct": -4.2,
        "nasdaq_drawdown_pct": -6.1,
        "index_gain_vs_prior_cycle_high": 4.0,
        "index_gain_from_recent_trough": 11.5,
        "distance_from_52w_high": -4.2,
        "index_extension_from_200d_pct": 4.8,
        "index_range_20d_pct": 6.4,
        "realized_vol_20d": 13.2,
        "previous_realized_vol_20d": 14.1,
        "consecutive_rate_cut_count": 0,
        "rate_trend": "steady",
        "media_hype_ratio": 1.7,
        "youtube_hype_ratio": 1.5,
        "institutional_support_score": 72,
        "insider_activity_score": 50,
        "options_activity_score": 66,
        "valuation_percentile_vs_5y": 87,
        "social_heat": "medium",
        "smart_money": {
            "institutional_13f": {
                "institution_name": "Mock Technology Fund",
                "issuer_name": "NVIDIA Corporation",
                "cusip": "67066G104",
                "shares": 850000,
                "market_value": 742000000,
                "quarter": "2026-Q1",
                "filing_date": "2026-05-15",
                "holder_count": 412,
                "holder_count_change": 18,
                "top_10_holder_concentration": 0.29,
                "quarterly_position_change_pct": 7.5,
                "institutional_ownership_proxy": 0.68,
                "peer_average_institutional_ownership": 0.58,
                "peer_average_quarterly_position_change_pct": 3.0,
                "sector_median_institutional_ownership": 0.61,
            },
            "form4_transactions": [
                {
                    "insider_name": "Mock Officer A",
                    "role": "Officer",
                    "transaction_code": "P",
                    "transaction_type": "accumulation",
                    "shares": 1500,
                    "price": 860.0,
                    "value": 1290000,
                    "transaction_date": "2026-03-20",
                    "filing_date": "2026-03-22",
                },
                {
                    "insider_name": "Mock Director B",
                    "role": "Director",
                    "transaction_code": "P",
                    "transaction_type": "accumulation",
                    "shares": 600,
                    "price": 870.0,
                    "value": 522000,
                    "transaction_date": "2026-04-02",
                    "filing_date": "2026-04-04",
                },
            ],
            "options_activity": {
                "option_volume": 185000,
                "open_interest": 52000,
                "call_put_ratio": 2.4,
                "implied_volatility": 0.51,
                "expiration_date": "2026-06-19",
                "abnormal_volume_ratio": 3.4,
                "direction_consistent_with_price_action": True,
            },
        },
        "missing_data": ["mock patent quality data", "mock executive retention data"],
    },
    "TSLA": {
        "company_name": "Tesla, Inc.",
        "sector": "Consumer Discretionary",
        "themes": ["humanoid robotics", "electric grid infrastructure"],
        "leadership_points": 13.0,
        "revenue_cagr_3y_pct": 18.6,
        "cash_to_market_cap_pct": 4.1,
        "revenue_growth_yoy_pct": [51.0, 19.0, -8.0],
        "free_cash_flow_margin_pct": 2.4,
        "net_debt_to_ebitda": -0.2,
        "founder_is_ceo": True,
        "net_insider_buy_value_180d": 0,
        "insider_buy_count_180d": 0,
        "vix": 17.8,
        "vix_recent_spike": False,
        "vix_trend": "stable",
        "vix_falling_from_spike": False,
        "fear_greed": 48,
        "sp500_drawdown_pct": -4.2,
        "nasdaq_drawdown_pct": -6.1,
        "index_gain_vs_prior_cycle_high": 4.0,
        "index_gain_from_recent_trough": 11.5,
        "distance_from_52w_high": -4.2,
        "index_extension_from_200d_pct": 4.8,
        "index_range_20d_pct": 6.4,
        "realized_vol_20d": 13.2,
        "previous_realized_vol_20d": 14.1,
        "consecutive_rate_cut_count": 0,
        "rate_trend": "steady",
        "media_hype_ratio": 2.8,
        "youtube_hype_ratio": 2.5,
        "institutional_support_score": 58,
        "insider_activity_score": 45,
        "options_activity_score": 82,
        "valuation_percentile_vs_5y": 72,
        "social_heat": "high",
        "smart_money": {
            "institutional_13f": {
                "institution_name": "Mock Consumer Fund",
                "issuer_name": "Tesla, Inc.",
                "cusip": "88160R101",
                "shares": 420000,
                "market_value": 112000000,
                "quarter": "2026-Q1",
                "filing_date": "2026-05-15",
                "holder_count": 305,
                "holder_count_change": -8,
                "top_10_holder_concentration": 0.41,
                "quarterly_position_change_pct": -11.0,
                "institutional_ownership_proxy": 0.49,
                "peer_average_institutional_ownership": 0.55,
                "peer_average_quarterly_position_change_pct": 1.5,
                "sector_median_institutional_ownership": 0.53,
                "major_holder_reduction": True,
            },
            "form4_transactions": [
                {
                    "insider_name": "Mock Officer C",
                    "role": "Officer",
                    "transaction_code": "S",
                    "transaction_type": "disposition",
                    "shares": 8000,
                    "price": 265.0,
                    "value": 2120000,
                    "transaction_date": "2026-03-18",
                    "filing_date": "2026-03-20",
                },
                {
                    "insider_name": "Mock Officer D",
                    "role": "Officer",
                    "transaction_code": "S",
                    "transaction_type": "disposition",
                    "shares": 5000,
                    "price": 255.0,
                    "value": 1275000,
                    "transaction_date": "2026-04-01",
                    "filing_date": "2026-04-03",
                },
            ],
            "options_activity": {
                "option_volume": 140000,
                "open_interest": 66000,
                "call_put_ratio": 0.8,
                "implied_volatility": 0.64,
                "expiration_date": "2026-06-19",
                "abnormal_volume_ratio": 2.2,
                "direction_consistent_with_price_action": False,
            },
        },
        "missing_data": ["mock segment margin detail", "mock current backlog detail"],
    },
}


DEFAULT_STOCK = {
    "company_name": "Mock US Listed Company",
    "sector": "Unclassified",
    "themes": ["future industry radar"],
    "leadership_points": 9.5,
    "revenue_cagr_3y_pct": 8.0,
    "cash_to_market_cap_pct": 2.5,
    "revenue_growth_yoy_pct": [6.0, 8.0, 9.0],
    "free_cash_flow_margin_pct": 4.0,
    "net_debt_to_ebitda": 2.8,
    "founder_is_ceo": False,
    "net_insider_buy_value_180d": 0,
    "insider_buy_count_180d": 0,
    "vix": 17.8,
    "vix_recent_spike": False,
    "vix_trend": "stable",
    "vix_falling_from_spike": False,
    "fear_greed": 48,
    "sp500_drawdown_pct": -4.2,
    "nasdaq_drawdown_pct": -6.1,
    "index_gain_vs_prior_cycle_high": 4.0,
    "index_gain_from_recent_trough": 11.5,
    "distance_from_52w_high": -4.2,
    "index_extension_from_200d_pct": 4.8,
    "index_range_20d_pct": 6.4,
    "realized_vol_20d": 13.2,
    "previous_realized_vol_20d": 14.1,
    "consecutive_rate_cut_count": 0,
    "rate_trend": "steady",
    "media_hype_ratio": 1.0,
    "youtube_hype_ratio": 1.0,
    "institutional_support_score": 40,
    "insider_activity_score": 50,
    "options_activity_score": 40,
    "valuation_percentile_vs_5y": 55,
    "social_heat": "low",
    "smart_money": MOCK_SMART_MONEY_SUMMARY,
    "missing_data": ["company-specific mock fixture"],
}
